version: '3.8'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - APP_ENV=development
      - DEBUG=True
  # depends_on:
  #   - db
  
  # db:
  #   image: postgres:13
  #   environment:
  #     - POSTGRES_USER=finutive
  #     - POSTGRES_PASSWORD=root
  #     - POSTGRES_DB=postgres
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: 